# Generated by Django 6.0.6 on 2026-06-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_task_created_at_module_task_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='user_slug_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
