# Generated by Django 6.0.6 on 2026-06-24 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_remove_task_created_at_remove_task_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='is_calendar_only',
            new_name='is_calendar_task',
        ),
        migrations.AlterField(
            model_name='task',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='planner.module'),
        ),
    ]
