# Generated by Django 6.0.6 on 2026-06-24 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_rename_is_calendar_only_task_is_calendar_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='dailystudymetric',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailystudymetric',
            name='user',
        ),
        migrations.CreateModel(
            name='StudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(auto_now_add=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_logs', to='planner.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CalendarTask',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='DailyStudyMetric',
        ),
    ]
