# Generated by Django 6.0.6 on 2026-06-25 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_remove_chatmessage_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_calendar_task',
        ),
    ]
